#
# Copyright (C) 2024 nosignals
#
name: Building nekoclash2
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'nekoclash version'
        required: true
        default: '1.1.11-beta'
        type: string
      changelog:
        description: 'Changelog'
        required: true
        default: ''
        type: string
        
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build nekoclash2
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 21.02.7
          - 23.05.0
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Preparing nekoclash
        run: |
              echo ""
              mkdir feeds artifacts
              cp -rf ./luci-app-nekoclash ./feeds
              echo "make package/luci-app-nekoclash/{clean,compile} -j$(nproc)"
              make package/luci-app-nekoclash/{clean,compile} -j$(nproc)
        
      - name: Building Luci nekoclash
        uses: nosignals/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-app-nekoclash
            echo "make package/luci-app-nekoclash/{clean,compile} -j$(nproc)"
            make package/luci-app-nekoclash/{clean,compile} -j$(nproc)
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-nekoclash-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app-nekoclash*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v3
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./luci-app-nekoclash-21.02.7_x86_64/* ./release/luci-app-nekoclash_${{ inputs.version }}_all_21_02.ipk
          cp -rf ./luci-app-nekoclash-23.05.0_x86_64/* ./release/luci-app-nekoclash_${{ inputs.version }}_all_23_05.ipk
  
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          tag: ${{ inputs.version }}
          file_glob: true
          body: |
            # LUCI APP nekoclash ${{ inputs.version }}
            Simple Clash TUN based Proxy
            ### Information
            - Changelog : 
              - ${{ inputs.changelog }}
            - Default Config : 
              - config.yaml : minimal Configs for nekoclash (only 1 rules) - Secret : ` sign `
              - nosignals.yaml : 2 rules can added (Block Host, Game) - Secret : ` telekulo `
            - Supported ARCH : 
              - ` arm64 / aarch64 `
              - ` x86_64 / amd64 `
            ### Dependency Requirement
            - ` bash, kmod-tun, php, php-cgi ` (install PHP Manually before install nekoclash)
            - OpenWrt 21: ` php7 php7-cgi iptables `
            - Openwrt 23: ` php8 php8-cgi nftables ` 
            
            ### Please Install with normal Connectivity
